export default {
      "expenditure":[
              {
                  "typeID":"e100",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_catering_selected.png",
                  "cid":1,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_catering_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_catering_normal.png",
                  "type":0,
                  "category_icon":"e_catering",
                  "category_name":"餐饮"
              },
              {
                  "typeID":"e101",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_shopping_selected.png",
                  "cid":2,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_shopping_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_shopping_normal.png",
                  "type":0,
                  "category_icon":"e_shopping",
                  "category_name":"购物"
              },
              {
                  "typeID":"e102",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_commodity_selected.png",
                  "cid":3,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_commodity_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_commodity_normal.png",
                  "type":0,
                  "category_icon":"e_commodity",
                  "category_name":"日用"
              },
              {
                  "typeID":"e103",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_traffic_selected.png",
                  "cid":4,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_traffic_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_traffic_normal.png",
                  "type":0,
                  "category_icon":"e_traffic",
                  "category_name":"交通"
              },
              {
                  "typeID":"e104",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_vegetable_selected.png",
                  "cid":5,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_vegetable_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_vegetable_normal.png",
                  "type":0,
                  "category_icon":"e_vegetable",
                  "category_name":"蔬菜"
              },
              {
                  "typeID":"e105",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_fruite_selected.png",
                  "cid":6,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_fruite_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_fruite_normal.png",
                  "type":0,
                  "category_icon":"e_fruite",
                  "category_name":"水果"
              },
              {
                  "typeID":"e106",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_snack_selected.png",
                  "cid":7,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_snack_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_snack_normal.png",
                  "type":0,
                  "category_icon":"e_snack",
                  "category_name":"零食"
              },
              {
                  "typeID":"e107",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_sport_selected.png",
                  "cid":8,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_sport_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_sport_normal.png",
                  "type":0,
                  "category_icon":"e_sport",
                  "category_name":"运动"
              },
              {
                  "typeID":"e108",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_entertainmente_selected.png",
                  "cid":9,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_entertainmente_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_entertainmente_normal.png",
                  "type":0,
                  "category_icon":"e_entertainmente",
                  "category_name":"娱乐"
              },
              {
                  "typeID":"e109",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_communicate_selected.png",
                  "cid":10,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_communicate_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_communicate_normal.png",
                  "type":0,
                  "category_icon":"e_communicate",
                  "category_name":"通讯"
              },
              {
                  "typeID":"e110",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_dress_selected.png",
                  "cid":11,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_dress_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_dress_normal.png",
                  "type":0,
                  "category_icon":"e_dress",
                  "category_name":"服饰"
              },
              {
                  "typeID":"e111",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_beauty_selected.png",
                  "cid":12,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_beauty_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_beauty_normal.png",
                  "type":0,
                  "category_icon":"e_beauty",
                  "category_name":"美容"
              },
              {
                  "typeID":"e112",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_house_selected.png",
                  "cid":13,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_house_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_house_normal.png",
                  "type":0,
                  "category_icon":"e_house",
                  "category_name":"住房"
              },
              {
                  "typeID":"e113",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_home_selected.png",
                  "cid":14,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_home_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_home_normal.png",
                  "type":0,
                  "category_icon":"e_home",
                  "category_name":"居家"
              },
              {
                  "typeID":"e114",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_child_selected.png",
                  "cid":15,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_child_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_child_normal.png",
                  "type":0,
                  "category_icon":"e_child",
                  "category_name":"孩子"
              },
              {
                  "typeID":"e115",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_elder_selected.png",
                  "cid":16,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_elder_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_elder_normal.png",
                  "type":0,
                  "category_icon":"e_elder",
                  "category_name":"长辈"
              },
              {
                  "typeID":"e116",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_social_selected.png",
                  "cid":17,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_social_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_social_normal.png",
                  "type":0,
                  "category_icon":"e_social",
                  "category_name":"社交"
              },
              {
                  "typeID":"e117",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_travel_selected.png",
                  "cid":18,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_travel_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_travel_normal.png",
                  "type":0,
                  "category_icon":"e_travel",
                  "category_name":"旅行"
              },
              {
                  "typeID":"e118",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_smoke_selected.png",
                  "cid":19,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_smoke_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_smoke_normal.png",
                  "type":0,
                  "category_icon":"e_smoke",
                  "category_name":"烟酒"
              },
              {
                  "typeID":"e119",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_digital_selected.png",
                  "cid":20,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_digital_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_digital_normal.png",
                  "type":0,
                  "category_icon":"e_digital",
                  "category_name":"数码"
              },
              {
                  "typeID":"e120",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_car_selected.png",
                  "cid":21,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_car_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_car_normal.png",
                  "type":0,
                  "category_icon":"e_car",
                  "category_name":"汽车"
              },
              {
                  "typeID":"e121",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_medical_selected.png",
                  "cid":22,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_medical_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_medical_normal.png",
                  "type":0,
                  "category_icon":"e_medical",
                  "category_name":"医疗"
              },
              {
                  "typeID":"e122",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_books_selected.png",
                  "cid":23,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_books_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_books_normal.png",
                  "type":0,
                  "category_icon":"e_books",
                  "category_name":"书籍"
              },
              {
                  "typeID":"e123",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_study_selected.png",
                  "cid":24,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_study_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_study_normal.png",
                  "type":0,
                  "category_icon":"e_study",
                  "category_name":"学习"
              },
              {
                  "typeID":"e124",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_pet_selected.png",
                  "cid":25,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_pet_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_pet_normal.png",
                  "type":0,
                  "category_icon":"e_pet",
                  "category_name":"宠物"
              },
              {
                  "typeID":"e125",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_money_selected.png",
                  "cid":26,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_money_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_money_normal.png",
                  "type":0,
                  "category_icon":"e_money",
                  "category_name":"礼金"
              },
              {
                  "typeID":"e126",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_gift_selected.png",
                  "cid":27,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_gift_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_gift_normal.png",
                  "type":0,
                  "category_icon":"e_gift",
                  "category_name":"礼物"
              },
              {
                  "typeID":"e127",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_office_selected.png",
                  "cid":28,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_office_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_office_normal.png",
                  "type":0,
                  "category_icon":"e_office",
                  "category_name":"办公"
              },
              {
                  "typeID":"e128",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_repair_selected.png",
                  "cid":29,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_repair_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_repair_normal.png",
                  "type":0,
                  "category_icon":"e_repair",
                  "category_name":"维修"
              },
              {
                  "typeID":"e129",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_donate_selected.png",
                  "cid":30,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_donate_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_donate_normal.png",
                  "type":0,
                  "category_icon":"e_donate",
                  "category_name":"捐赠"
              },
              {
                  "typeID":"e130",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_lottery_selected.png",
                  "cid":31,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_lottery_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_lottery_normal.png",
                  "type":0,
                  "category_icon":"e_lottery",
                  "category_name":"彩票"
              },
              {
                  "typeID":"e1131",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_friend_selected.png",
                  "cid":32,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_friend_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_friend_normal.png",
                  "type":0,
                  "category_icon":"e_friend",
                  "category_name":"亲友"
              },
              {
                  "typeID":"e1132",
                  "selected_url":"http://c.rs.shayujizhang.com/category_e_express_selected.png",
                  "cid":33,
                  "s_url":"http://c.rs.shayujizhang.com/category_e_express_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_e_express_normal.png",
                  "type":0,
                  "category_icon":"e_express",
                  "category_name":"快递"
              }
          ],
          "income":[
              {
                  "typeID":"i100",
                  "selected_url":"http://c.rs.shayujizhang.com/category_i_wage_selected.png",
                  "cid":34,
                  "s_url":"http://c.rs.shayujizhang.com/category_i_wage_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_i_wage_normal.png",
                  "type":2,
                  "category_icon":"i_wage",
                  "category_name":"工资"
              },
              {
                  "typeID":"i101",
                  "selected_url":"http://c.rs.shayujizhang.com/category_i_parttimework_selected.png",
                  "cid":35,
                  "s_url":"http://c.rs.shayujizhang.com/category_i_parttimework_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_i_parttimework_normal.png",
                  "type":2,
                  "category_icon":"i_parttimework",
                  "category_name":"兼职"
              },
              {
                  "typeID":"i102",
                  "selected_url":"http://c.rs.shayujizhang.com/category_i_finance_selected.png",
                  "cid":36,
                  "s_url":"http://c.rs.shayujizhang.com/category_i_finance_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_i_finance_normal.png",
                  "type":2,
                  "category_icon":"i_finance",
                  "category_name":"理财"
              },
              {
                  "typeID":"i103",
                  "selected_url":"http://c.rs.shayujizhang.com/category_i_money_selected.png",
                  "cid":37,
                  "s_url":"http://c.rs.shayujizhang.com/category_i_money_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_i_money_normal.png",
                  "type":2,
                  "category_icon":"i_money",
                  "category_name":"礼金"
              },
              {
                  "typeID":"i104",
                  "selected_url":"http://c.rs.shayujizhang.com/category_i_other_selected.png",
                  "cid":38,
                  "s_url":"http://c.rs.shayujizhang.com/category_i_other_s.png",
                  "normal_url":"http://c.rs.shayujizhang.com/category_i_other_normal.png",
                  "type":2,
                  "category_icon":"i_other",
                  "category_name":"其它"
              }
          ]
  }